PavlicWebShop/Controllers/AdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PavlicWebShop.Models;
using PavlicWebShop.Models.Binding;
using PavlicWebShop.Services.Implementation;
using PavlicWebShop.Services.Interface;
using Microsoft.AspNetCore.Identity;
using PavlicWebShop.Models.Dbo;

namespace PavlicWebShop.Controllers
{
    [Authorize(Roles = Roles.Admin)]
    public class AdminController : Controller
    {
        private readonly IProductService productService;
        private readonly IMapper mapper;
        private readonly IUserService userSevice;
        private readonly SignInManager<ApplicationUser> signInManager;

        public AdminController(IProductService productService, IMapper mapper, IUserService userSevice, SignInManager<ApplicationUser> signInManager)
        {
            this.mapper = mapper;
            this.productService = productService;
            this.userSevice = userSevice;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> Users()
        {
            var users = await userSevice.GetUsers();
            return View(users);
        }


        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await userSevice.GetUser(id);
            return View(user);
        }


        [HttpPost]
        public async Task<IActionResult> EditUser(UserAdminUpdateBinding model)
        {
            await userSevice.UpdateUser(model);
            return RedirectToAction("Users");
        }

        [HttpGet]
        public async Task<IActionResult> UserDetails(string id)
        {
            var user = await userSevice.GetUser(id);
            return View(user);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            await userSevice.DeleteUserAsync(id);
            return RedirectToAction("Users");
        }

        //[HttpPost]
        //public async Task<IActionResult> CreateNewUser(UserAdminBinding model)
        //{
        //    await userSevice.CreateUserAsync(model);
        //    return RedirectToAction("Users");
        //}

        [HttpGet]
        public async Task<IActionResult> CreateNewUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateNewUser(UserAdminBinding model)
        {
            await userSevice.CreateUserAsync(model);
            return RedirectToAction("Users");
        }





        [HttpGet]
        public async Task<IActionResult> ProductAdministration()
        {
            var products = await productService.GetProducts();
            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int id)
        {
            var product = await productService.GetProduct(id);
            var model = mapper.Map<ProductUpdateBinding>(product);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(ProductUpdateBinding model)
        {
            var product = await productService.UpdateProduct(model);
            return RedirectToAction("ProductAdministration");
        }

        [HttpGet]
        public async Task<IActionResult> AddProduct()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(ProductBinding model)
        {
            await productService.AddProduct(model);
            return RedirectToAction("ProductAdministration");
        }

        [HttpGet]
        public async Task<IActionResult> AddProductCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddProductCategory(ProductCategoryBinding model)
        {
            await productService.AddProductCategory(model);
            return RedirectToAction("ProductAdministration");
        }
    }
}

PavlicWebShop/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PavlicWebShop.Models.Binding;
using PavlicWebShop.Services.Interface;

namespace PavlicWebShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly IMapper mapper;

        public ProductController(IProductService productService, IMapper mapper)
        {
            this.mapper = mapper;
            this.productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> ProductsList()
        {
            var products = await productService.GetProducts();
            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int id)
        {
            var product = await productService.GetProduct(id);
            var model = mapper.Map<ProductUpdateBinding>(product);
            return View(model);
        }

        public async Task<IActionResult> DetailsProduct(int id)
        {
            var product = await productService.GetProduct(id);
            var model = mapper.Map<ProductUpdateBinding>(product);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(ProductUpdateBinding model)
        {
            var product = await productService.UpdateProduct(model);

            return RedirectToAction("ProductsList");
        }

        [HttpGet]
        public async Task<IActionResult> AddProduct()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(ProductBinding model)
        {
            await productService.AddProduct(model);
            return RedirectToAction("ProductsList");

        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            await productService.DeleteProduct(id);
            return RedirectToAction("ProductsList");
        }

        [HttpGet]
        public async Task<IActionResult> AddProductCategory()
        {
            return View();
        }

        //[HttpGet]
        //public async Task<IActionResult> ProductsByCategory(int productCategoryId)
        //{
        //    var products = await productService.GetProductByCategory(productCategoryId);
        //    return View(products);
        //}

        [HttpGet]
        public async Task<IActionResult> ProductsByCategory(int id)
        {
            var products = await productService.GetProductByCategory(id);
            return View(products);
        }

        [HttpPost]
        public async Task<IActionResult> AddProductCategory(ProductCategoryBinding model)
        {
            await productService.AddProductCategory(model);
            return RedirectToAction("ProductCategoryList");
        }

        [HttpGet]
        public async Task<IActionResult> ProductCategorysList()
        {
            var productCategorys = await productService.GetProductCategorys();
            return View(productCategorys);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProductCategory(int id)
        {
            var productCategorys = await productService.GetProductCategory(id);
            var model = mapper.Map<ProductCategoryUpdateBinding>(productCategorys);
            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductCategory(ProductCategoryUpdateBinding model)
        {
            var productCategorys = await productService.UpdateProductCategory(model);
            return RedirectToAction("ProductCategorysList");
        }
    }
}

PavlicWebShop/Controllers/SharedController.cs
using Microsoft.AspNetCore.Mvc;
using PavlicWebShop.Services.Interface;

namespace PavlicWebShop.Controllers
{
    [Route("[controller]")]
    public class SharedController : ControllerBase
    {
        private readonly IFileStorageService fileStorageService;

        public SharedController(IFileStorageService fileStorageService)
        {
            this.fileStorageService = fileStorageService;
        }

        [Route("files/{id}")]
        public async Task<IActionResult> GetFile(int id)
        {

            var img = await fileStorageService.GetFile(id);
            if (img == null)
            {
                return NoContent();
            }
            Response.Headers.Add("Content-Disposition", img.ContentDisposition.ToString());

            return File(img.FileStream, "image/" + img.FileExtension.Replace(".", string.Empty));
        }

        [HttpDelete]
        [Route("file/{id}")]
        public async Task<IActionResult> DeleteFile(int id)
        {
            if (await fileStorageService.DeleteFile(id))
            {
                return Ok(new { Msg = "deleted!" });
            }

            return BadRequest(new { Msg = "Error!" });
        }
    }
}

PavlicWebShop/Views/Shared/_Footer.cshtml
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022 Ivan Pavlić</strong>
</footer>

PavlicWebShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PavlicWebShop.Models.Binding
@using PavlicWebShop.Models.Dbo
@using PavlicWebShop.Services.Interface;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IUserService appUserManager
@inject IProductService productService

@{
    var productCategory = await productService.GetProductCategorys();
}

@{

    var user = await UserManager.GetUserAsync(User);

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PavlicWebShop</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    @await RenderSectionAsync("Styles", required: false)
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">



    <!-- Content Wrapper. Contains page content -->
    <div class="wrapper">
        <!-- Navbar -->
        <partial name="_Navbar" />
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <partial name="_Sidebar" />

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <p></p>
                    @RenderBody()
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->


        <partial name="_Footer" />
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
     <!-- DataTables  & Plugins -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PavlicWebShop/Views/Shared/_Navbar.cshtml
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="@Url.Action("Index", "Home")" class="nav-link">Home</a>
      </li>

    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
   <partial name="_LoginPartial" />
      </ul>
  </nav>
  <!-- /.navbar -->

PavlicWebShop/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Identity
@using PavlicWebShop.Models.Binding
@using PavlicWebShop.Models.Dbo
@using PavlicWebShop.Services.Interface;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IUserService appUserManager
@inject IProductService productService

@{
    var productCategory = await productService.GetProductCategorys();
}
@{
    var user = await UserManager.GetUserAsync(User);
}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="~/Home/Index" class="brand-link">
        <img src="~/Plogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Pavlic OPG</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->

        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            @if (user != null)
            {
                <div class="image">
                    <img src="~/user.png" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">@user.Firstname @user.Lastname</a>
                </div>
            }
        </div>


        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item menu">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cube"></i>
                        <p>
                            Products
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            @foreach (var category in productCategory)
                            {
                                <a href="@Url.Action("ProductsByCategory", "Home",new {id = category.Id})" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>@category.Title</p>
                                </a>
                            }
                        </li>
                    </ul>
                </li>
                @if (user != null)
                {
                    var userRoles = await UserManager.GetRolesAsync(user);

                    @switch (userRoles[0])
                    {
                        case Roles.Admin:
                            <li class="nav-item menu">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-clone"></i>
                                    <p>
                                        Administration
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="@Url.Action("ProductsList", "Product")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Products List</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("ProductCategorysList", "Product")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Categorys List</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Users", "Admin")" class="nav-link">
                                    <i class="nav-icon fas  fa-user"></i>
                                    <p>Users</p>
                                </a>
                            </li>
                            break;

                        case Roles.Employee:
                            <li class="nav-item menu">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-clone"></i>
                                    <p>
                                        Products Administration
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="@Url.Action("ProductsList", "Product")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Products List</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("ProductCategorysList", "Product")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Categorys List</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            break;
                    }
                }

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>